# backend/services/youtube_publishing_service.py
import os
import logging
from typing import Dict, Any, List

logger = logging.getLogger("vyaparai.services.youtube_publishing")

class YouTubePublishingService:
    def __init__(self):
        self.api_available = False
        # Check if google api client is installed
        try:
            from googleapiclient.discovery import build
            from google_auth_oauthlib.flow import InstalledAppFlow
            from google.auth.transport.requests import Request
            import pickle
            self.api_available = True
            logger.info("Google API Client library detected for YouTube uploading.")
        except ImportError:
            logger.info("Google API Client not installed. Running YouTube publisher in simulated mode.")

    def publish_video(
        self, 
        video_path: str, 
        title: str, 
        description: str, 
        hashtags: List[str],
        thumbnail_path: str = None
    ) -> Dict[str, Any]:
        """
        Uploads a video to YouTube with metadata.
        If credentials/secrets are not found, falls back to simulated upload.
        """
        logger.info(f"Publishing video to YouTube: \"{title}\"")
        
        tags_str = " ".join([f"#{t}" for t in hashtags])
        full_desc = f"{description}\n\n{tags_str}\n\nGenerated by VyaparAI.in"
        
        client_secrets_path = "client_secrets.json"
        
        if self.api_available and os.path.exists(client_secrets_path):
            try:
                # Real OAuth2 upload flow
                import pickle
                from googleapiclient.discovery import build
                from googleapiclient.http import MediaFileUpload
                from google_auth_oauthlib.flow import InstalledAppFlow
                
                scopes = ["https://www.googleapis.com/auth/youtube.upload"]
                creds = None
                
                # Check for cached tokens
                if os.path.exists("token.pickle"):
                    with open("token.pickle", "rb") as token:
                        creds = pickle.load(token)
                        
                if not creds or not creds.valid:
                    if creds and creds.expired and creds.refresh_token:
                        from google.auth.transport.requests import Request
                        creds.refresh(Request())
                    else:
                        flow = InstalledAppFlow.from_client_secrets_file(client_secrets_path, scopes)
                        creds = flow.run_local_server(port=0)
                    with open("token.pickle", "wb") as token:
                        pickle.dump(creds, token)
                        
                youtube = build("youtube", "v3", credentials=creds)
                
                body = {
                    "snippet": {
                        "title": title[:100],
                        "description": full_desc[:5000],
                        "tags": hashtags,
                        "categoryId": "22" # People & Blogs
                    },
                    "status": {
                        "privacyStatus": "public" # public, private, unlisted
                    }
                }
                
                media = MediaFileUpload(
                    video_path, 
                    mimetype="video/mp4", 
                    chunksize=-1, 
                    resumable=True
                )
                
                request = youtube.videos().insert(
                    part="snippet,status",
                    body=body,
                    media_body=media
                )
                
                logger.info("Uploading video file to YouTube...")
                response = request.execute()
                video_id = response.get("id")
                video_url = f"https://www.youtube.com/watch?v={video_id}"
                
                logger.info(f"Successfully uploaded to YouTube. Video ID: {video_id}")
                return {
                    "status": "success",
                    "youtube_id": video_id,
                    "youtube_url": video_url,
                    "simulated": False
                }
            except Exception as e:
                logger.error(f"YouTube real upload failed: {e}. Falling back to sandbox simulation.")

        # Sandbox Fallback Mode
        import uuid
        mock_id = f"YOUTUBE_{uuid.uuid4().hex[:11].upper()}"
        mock_url = f"https://www.youtube.com/watch?v={mock_id}"
        
        logger.info(f"[SANDBOX PUBLISHER] Simulated video upload complete! Assigned URL: {mock_url}")
        return {
            "status": "success",
            "youtube_id": mock_id,
            "youtube_url": mock_url,
            "simulated": True
        }

youtube_publish_svc = YouTubePublishingService()
