# backend/services/youtube_publishing_service.py
import os
import logging
from typing import Dict, Any, List

logger = logging.getLogger("vyaparai.services.youtube_publishing")

class YouTubePublishingService:
    def __init__(self):
        self.api_available = False
        # Check if google api client is installed
        try:
            from googleapiclient.discovery import build
            from google_auth_oauthlib.flow import InstalledAppFlow
            from google.auth.transport.requests import Request
            import pickle
            self.api_available = True
            logger.info("Google API Client library detected for YouTube uploading.")
        except ImportError:
            logger.info("Google API Client not installed. Running YouTube publisher in simulated mode.")

    def publish_video(
        self, 
        video_path: str, 
        title: str, 
        description: str, 
        hashtags: List[str],
        thumbnail_path: str = None,
        progress_callback = None,
        simulate: bool = False
    ) -> Dict[str, Any]:
        """
        Uploads a video to YouTube with metadata.
        If credentials/secrets are not found or simulate is True, falls back to simulated upload.
        """
        logger.info(f"Publishing video to YouTube: \"{title}\" (simulate={simulate})")
        
        tags_str = " ".join([f"#{t}" for t in hashtags])
        full_desc = f"{description}\n\n{tags_str}\n\nGenerated by VyaparAI.in"
        
        if self.api_available and not simulate:
            try:
                from googleapiclient.discovery import build
                from googleapiclient.http import MediaFileUpload
                from google.oauth2.credentials import Credentials
                from backend.services.supabase_service import supabase_svc
                
                channels = supabase_svc.get_youtube_channels()
                if not channels:
                    raise Exception("No connected YouTube channel found in the database. Please connect via dashboard.")
                    
                channel = channels[0]
                creds = Credentials(
                    token=channel.get("access_token"),
                    refresh_token=channel.get("refresh_token"),
                    token_uri=channel.get("token_uri") or "https://oauth2.googleapis.com/token",
                    client_id=channel.get("client_id"),
                    client_secret=channel.get("client_secret"),
                    scopes=channel.get("scopes") or ["https://www.googleapis.com/auth/youtube.force-ssl"]
                )
                
                youtube = build("youtube", "v3", credentials=creds)
                
                body = {
                    "snippet": {
                        "title": title[:100],
                        "description": full_desc[:5000],
                        "tags": hashtags,
                        "categoryId": "22"
                    },
                    "status": {
                        "privacyStatus": "public",
                        "selfDeclaredMadeForKids": False
                    }
                }
                
                # Resumable chunked upload configuration (1MB chunk size)
                media = MediaFileUpload(
                    video_path, 
                    mimetype="video/mp4", 
                    chunksize=1024*1024, 
                    resumable=True
                )
                
                request = youtube.videos().insert(
                    part="snippet,status",
                    body=body,
                    media_body=media
                )
                
                logger.info("Uploading video file to YouTube in chunks...")
                response = None
                while response is None:
                    status, response = request.next_chunk()
                    if status and progress_callback:
                        progress = int(status.progress() * 100)
                        progress_callback(progress)
                        logger.info(f"YouTube Upload Progress: {progress}%")
                
                video_id = response.get("id")
                video_url = f"https://www.youtube.com/watch?v={video_id}"
                
                logger.info(f"Successfully uploaded to YouTube. Video ID: {video_id}")
                return {
                    "status": "success",
                    "youtube_id": video_id,
                    "youtube_url": video_url,
                    "simulated": False
                }
            except Exception as e:
                logger.error(f"YouTube real upload failed: {e}")
                raise e

        # Sandbox Fallback Mode
        import uuid
        mock_id = f"YOUTUBE_{uuid.uuid4().hex[:11].upper()}"
        mock_url = f"https://www.youtube.com/watch?v={mock_id}"
        
        logger.info(f"[SANDBOX PUBLISHER] Simulated video upload initialized: {mock_url}")
        return {
            "status": "success",
            "youtube_id": mock_id,
            "youtube_url": mock_url,
            "simulated": True
        }

    def check_video_processing_status(
        self, 
        video_id: str, 
        channel_info: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Queries YouTube Data API to check processing, upload, and privacy statuses of a video.
        """
        try:
            from google.oauth2.credentials import Credentials
            from googleapiclient.discovery import build
            
            creds = Credentials(
                token=channel_info.get("access_token"),
                refresh_token=channel_info.get("refresh_token"),
                token_uri=channel_info.get("token_uri") or "https://oauth2.googleapis.com/token",
                client_id=channel_info.get("client_id"),
                client_secret=channel_info.get("client_secret"),
                scopes=channel_info.get("scopes") or ["https://www.googleapis.com/auth/youtube.force-ssl"]
            )
            youtube = build("youtube", "v3", credentials=creds)
            
            request = youtube.videos().list(
                part="status,processingDetails",
                id=video_id
            )
            response = request.execute()
            
            if response.get("items"):
                item = response["items"][0]
                status_snippet = item.get("status", {})
                processing_details = item.get("processingDetails", {}) or {}
                
                return {
                    "status": "success",
                    "upload_status": status_snippet.get("uploadStatus"),
                    "privacy_status": status_snippet.get("privacyStatus"),
                    "processing_status": processing_details.get("processingStatus"),
                    "rejection_reason": status_snippet.get("rejectionReason"),
                    "failure_reason": status_snippet.get("failureReason"),
                    "time_left_ms": processing_details.get("timeLeftMs"),
                    "parts_processed": processing_details.get("partsProcessed"),
                    "parts_total": processing_details.get("partsTotal")
                }
            return {"status": "not_found", "error": "Video details not found on YouTube"}
        except Exception as e:
            logger.error(f"Failed to fetch YouTube video status: {e}")
            return {"status": "error", "error": str(e)}

youtube_publish_svc = YouTubePublishingService()
